create table photo
(
    id       int8 generated by default as identity,
    data     oid,
    filename varchar(255),
    message  varchar(2048),
    tag      varchar(255),
    type     varchar(255),
    user_id  int8,
    primary key (id)
);
create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);
create table usr
(
    id       int8 generated by default as identity,
    password varchar(255),
    username varchar(255),
    email varchar(255),
    activation_code varchar(255),
    primary key (id)
);
alter table if exists photo
    add constraint photo_user_from_key foreign key (user_id) references usr;
alter table if exists user_role
    add constraint user_role_user_fk foreign key (user_id) references usr;
insert into usr (id,password, username) values (1,1, 'Admin');
